# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-26 02:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('RI', 'Rice'), ('WH', 'Wheat'), ('PL', 'Pulses'), ('MZ', 'Maize'), ('ML', 'Millets')], max_length=2)),
                ('city', models.CharField(choices=[('CH', 'Chennai'), ('MB', 'Mumbai'), ('KT', 'Kokkatta'), ('DH', 'Delhi'), ('HD', 'Hyderbad'), ('BL', 'Banglore')], max_length=2)),
                ('volume', models.PositiveIntegerField()),
                ('delivery_date', models.DateField()),
                ('entry', models.CharField(choices=[('O', 'Order'), ('P', 'Produce')], max_length=1)),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
