# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-26 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crop', models.CharField(choices=[('RI', 'Rice'), ('WH', 'Wheat'), ('PL', 'Pulses'), ('MZ', 'Maize'), ('ML', 'Millets')], max_length=2)),
                ('city', models.CharField(choices=[('CH', 'Chennai'), ('MB', 'Mumbai'), ('KT', 'Kokkatta'), ('DH', 'Delhi'), ('HD', 'Hyderbad'), ('BL', 'Banglore')], max_length=2)),
                ('volume', models.PositiveIntegerField()),
                ('delivery_date', models.DateField()),
            ],
        ),
    ]
