# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-25 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200)),
                ('contact_number', models.CharField(max_length=12)),
                ('role', models.CharField(max_length=200)),
                ('aggriculture_produce', models.CharField(max_length=200)),
                ('variety', models.CharField(max_length=200)),
                ('quantity', models.PositiveIntegerField()),
                ('quality_specification', models.CharField(max_length=200)),
                ('delivery_place', models.CharField(max_length=200)),
                ('expected_date_of_delivery', models.DateField()),
            ],
        ),
    ]
